version: '4'

services:
  postgresql:
    image: postgres
    container_name: cryptomus
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0302
      - POSTGRES_DATABASE=cryptomus
    command: postgres
    restart: always